<?php

declare(strict_types=1);

namespace UMA\Uuid\Tests;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use UMA\Uuid\CombGenerator;
use UMA\Uuid\Uuid;
use UMA\Uuid\UuidGenerator;
use UMA\Uuid\Version1Generator;
use UMA\Uuid\Version4Generator;

final class UuidGeneratorTest extends TestCase
{
    private const ITERATIONS = 10000;

    /**
     * @param int $version the expected version to be found
     *                     on all Uuids generated by $sut
     */
    #[DataProvider('formatAndCollisionsProvider')]
    public function testFormatAndCollisions(UuidGenerator $sut, int $version): void
    {
        $seen = [];

        for ($i = 0; $i < self::ITERATIONS; ++$i) {
            $str = $sut->generate()->asString();

            self::assertTrue(Uuid::isUuid($str));
            self::assertSame((string) $version, $str[14], "Uuid version is not the expected '$version': $str");
            self::assertContains($str[19], ['8', '9', 'a', 'b'], "Uuid variant is not the expected '10xx': $str");
            self::assertArrayNotHasKey($str, $seen, "OMG FOUND A COLLISION: $str");

            $seen[$str] = true;
        }
    }

    public static function formatAndCollisionsProvider(): array
    {
        return [
            [new CombGenerator(), 4],
            [new Version1Generator('01:23:45:67:89:ab'), 1],
            [new Version4Generator(), 4],
        ];
    }
}
